/* This file is generated by venus-protocol.  See vn_protocol_driver.h. */

/*
 * Copyright 2020 Google LLC
 * SPDX-License-Identifier: MIT
 */

#ifndef VN_PROTOCOL_DRIVER_DEVICE_GENERATED_COMMANDS_H
#define VN_PROTOCOL_DRIVER_DEVICE_GENERATED_COMMANDS_H

#include "vn_ring.h"
#include "vn_protocol_driver_structs.h"

/* struct VkGeneratedCommandsMemoryRequirementsInfoEXT chain */

static inline size_t
vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(const void *val)
{
    const void *pnext = val;
    size_t size = 0;

    while (pnext) {
        switch ((int32_t)(*(const VkStructureType *)pnext)) {
        case VK_STRUCTURE_TYPE_GENERATED_COMMANDS_PIPELINE_INFO_EXT:
            if (!vn_cs_renderer_protocol_has_extension(573 /* VK_EXT_device_generated_commands */))
                break;
            size += vn_sizeof_simple_pointer(pnext);
            size += vn_sizeof_VkStructureType(pnext);
            size += vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(((const VkGeneratedCommandsPipelineInfoEXT *)pnext)->pNext);
            size += vn_sizeof_VkGeneratedCommandsPipelineInfoEXT_self(pnext);
            return size;
        case VK_STRUCTURE_TYPE_GENERATED_COMMANDS_SHADER_INFO_EXT:
            if (!vn_cs_renderer_protocol_has_extension(573 /* VK_EXT_device_generated_commands */))
                break;
            size += vn_sizeof_simple_pointer(pnext);
            size += vn_sizeof_VkStructureType(pnext);
            size += vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(((const VkGeneratedCommandsShaderInfoEXT *)pnext)->pNext);
            size += vn_sizeof_VkGeneratedCommandsShaderInfoEXT_self(pnext);
            return size;
        default:
            /* ignore unknown/unsupported struct */
            break;
        }
        memcpy(&pnext, (const char *)pnext + offsetof(VkBaseInStructure, pNext), sizeof(pnext));
    }

    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_self(const VkGeneratedCommandsMemoryRequirementsInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkIndirectExecutionSetEXT(&val->indirectExecutionSet);
    size += vn_sizeof_VkIndirectCommandsLayoutEXT(&val->indirectCommandsLayout);
    size += vn_sizeof_uint32_t(&val->maxSequenceCount);
    size += vn_sizeof_uint32_t(&val->maxDrawCount);
    return size;
}

static inline size_t
vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT(const VkGeneratedCommandsMemoryRequirementsInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    const void *pnext = val;

    while (pnext) {
        switch ((int32_t)(*(const VkStructureType *)pnext)) {
        case VK_STRUCTURE_TYPE_GENERATED_COMMANDS_PIPELINE_INFO_EXT:
            if (!vn_cs_renderer_protocol_has_extension(573 /* VK_EXT_device_generated_commands */))
                break;
            vn_encode_simple_pointer(enc, pnext);
            vn_encode_VkStructureType(enc, pnext);
            vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(enc, ((const VkGeneratedCommandsPipelineInfoEXT *)pnext)->pNext);
            vn_encode_VkGeneratedCommandsPipelineInfoEXT_self(enc, pnext);
            return;
        case VK_STRUCTURE_TYPE_GENERATED_COMMANDS_SHADER_INFO_EXT:
            if (!vn_cs_renderer_protocol_has_extension(573 /* VK_EXT_device_generated_commands */))
                break;
            vn_encode_simple_pointer(enc, pnext);
            vn_encode_VkStructureType(enc, pnext);
            vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(enc, ((const VkGeneratedCommandsShaderInfoEXT *)pnext)->pNext);
            vn_encode_VkGeneratedCommandsShaderInfoEXT_self(enc, pnext);
            return;
        default:
            /* ignore unknown/unsupported struct */
            break;
        }
        memcpy(&pnext, (const char *)pnext + offsetof(VkBaseInStructure, pNext), sizeof(pnext));
    }

    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_self(struct vn_cs_encoder *enc, const VkGeneratedCommandsMemoryRequirementsInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkIndirectExecutionSetEXT(enc, &val->indirectExecutionSet);
    vn_encode_VkIndirectCommandsLayoutEXT(enc, &val->indirectCommandsLayout);
    vn_encode_uint32_t(enc, &val->maxSequenceCount);
    vn_encode_uint32_t(enc, &val->maxDrawCount);
}

static inline void
vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT(struct vn_cs_encoder *enc, const VkGeneratedCommandsMemoryRequirementsInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_GENERATED_COMMANDS_MEMORY_REQUIREMENTS_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_GENERATED_COMMANDS_MEMORY_REQUIREMENTS_INFO_EXT });
    vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT_self(enc, val);
}

/* struct VkIndirectCommandsPushConstantTokenEXT */

static inline size_t
vn_sizeof_VkIndirectCommandsPushConstantTokenEXT(const VkIndirectCommandsPushConstantTokenEXT *val)
{
    size_t size = 0;
    size += vn_sizeof_VkPushConstantRange(&val->updateRange);
    return size;
}

static inline void
vn_encode_VkIndirectCommandsPushConstantTokenEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsPushConstantTokenEXT *val)
{
    vn_encode_VkPushConstantRange(enc, &val->updateRange);
}

/* struct VkIndirectCommandsVertexBufferTokenEXT */

static inline size_t
vn_sizeof_VkIndirectCommandsVertexBufferTokenEXT(const VkIndirectCommandsVertexBufferTokenEXT *val)
{
    size_t size = 0;
    size += vn_sizeof_uint32_t(&val->vertexBindingUnit);
    return size;
}

static inline void
vn_encode_VkIndirectCommandsVertexBufferTokenEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsVertexBufferTokenEXT *val)
{
    vn_encode_uint32_t(enc, &val->vertexBindingUnit);
}

/* struct VkIndirectCommandsIndexBufferTokenEXT */

static inline size_t
vn_sizeof_VkIndirectCommandsIndexBufferTokenEXT(const VkIndirectCommandsIndexBufferTokenEXT *val)
{
    size_t size = 0;
    size += vn_sizeof_VkIndirectCommandsInputModeFlagBitsEXT(&val->mode);
    return size;
}

static inline void
vn_encode_VkIndirectCommandsIndexBufferTokenEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsIndexBufferTokenEXT *val)
{
    vn_encode_VkIndirectCommandsInputModeFlagBitsEXT(enc, &val->mode);
}

/* struct VkIndirectCommandsExecutionSetTokenEXT */

static inline size_t
vn_sizeof_VkIndirectCommandsExecutionSetTokenEXT(const VkIndirectCommandsExecutionSetTokenEXT *val)
{
    size_t size = 0;
    size += vn_sizeof_VkIndirectExecutionSetInfoTypeEXT(&val->type);
    size += vn_sizeof_VkFlags(&val->shaderStages);
    return size;
}

static inline void
vn_encode_VkIndirectCommandsExecutionSetTokenEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsExecutionSetTokenEXT *val)
{
    vn_encode_VkIndirectExecutionSetInfoTypeEXT(enc, &val->type);
    vn_encode_VkFlags(enc, &val->shaderStages);
}

/* union VkIndirectCommandsTokenDataEXT */

static inline size_t
vn_sizeof_VkIndirectCommandsTokenDataEXT(const VkIndirectCommandsTokenDataEXT *val, VkIndirectCommandsTokenTypeEXT tag)
{
    size_t size = vn_sizeof_VkIndirectCommandsTokenTypeEXT(&tag);
    switch (tag) {
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT:
        size += vn_sizeof_simple_pointer(val->pPushConstant);
        if (val->pPushConstant)
            size += vn_sizeof_VkIndirectCommandsPushConstantTokenEXT(val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT:
        size += vn_sizeof_simple_pointer(val->pPushConstant);
        if (val->pPushConstant)
            size += vn_sizeof_VkIndirectCommandsPushConstantTokenEXT(val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_DATA_EXT:
        size += vn_sizeof_simple_pointer(val->pPushConstant);
        if (val->pPushConstant)
            size += vn_sizeof_VkIndirectCommandsPushConstantTokenEXT(val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_DATA_SEQUENCE_INDEX_EXT:
        size += vn_sizeof_simple_pointer(val->pPushConstant);
        if (val->pPushConstant)
            size += vn_sizeof_VkIndirectCommandsPushConstantTokenEXT(val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT:
        size += vn_sizeof_simple_pointer(val->pVertexBuffer);
        if (val->pVertexBuffer)
            size += vn_sizeof_VkIndirectCommandsVertexBufferTokenEXT(val->pVertexBuffer);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXT:
        size += vn_sizeof_simple_pointer(val->pIndexBuffer);
        if (val->pIndexBuffer)
            size += vn_sizeof_VkIndirectCommandsIndexBufferTokenEXT(val->pIndexBuffer);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT:
        size += vn_sizeof_simple_pointer(val->pExecutionSet);
        if (val->pExecutionSet)
            size += vn_sizeof_VkIndirectCommandsExecutionSetTokenEXT(val->pExecutionSet);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_NV_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_TRACE_RAYS2_EXT:
        /* This selector has no union payload. */
        break;
    default:
        assert(false);
        break;
    }
    return size;
}

static inline void
vn_encode_VkIndirectCommandsTokenDataEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsTokenDataEXT *val, VkIndirectCommandsTokenTypeEXT tag)
{
    vn_encode_VkIndirectCommandsTokenTypeEXT(enc, &tag);
    switch (tag) {
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_CONSTANT_EXT:
        if (vn_encode_simple_pointer(enc, val->pPushConstant))
            vn_encode_VkIndirectCommandsPushConstantTokenEXT(enc, val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_SEQUENCE_INDEX_EXT:
        if (vn_encode_simple_pointer(enc, val->pPushConstant))
            vn_encode_VkIndirectCommandsPushConstantTokenEXT(enc, val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_DATA_EXT:
        if (vn_encode_simple_pointer(enc, val->pPushConstant))
            vn_encode_VkIndirectCommandsPushConstantTokenEXT(enc, val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_PUSH_DATA_SEQUENCE_INDEX_EXT:
        if (vn_encode_simple_pointer(enc, val->pPushConstant))
            vn_encode_VkIndirectCommandsPushConstantTokenEXT(enc, val->pPushConstant);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_VERTEX_BUFFER_EXT:
        if (vn_encode_simple_pointer(enc, val->pVertexBuffer))
            vn_encode_VkIndirectCommandsVertexBufferTokenEXT(enc, val->pVertexBuffer);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_INDEX_BUFFER_EXT:
        if (vn_encode_simple_pointer(enc, val->pIndexBuffer))
            vn_encode_VkIndirectCommandsIndexBufferTokenEXT(enc, val->pIndexBuffer);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_EXECUTION_SET_EXT:
        if (vn_encode_simple_pointer(enc, val->pExecutionSet))
            vn_encode_VkIndirectCommandsExecutionSetTokenEXT(enc, val->pExecutionSet);
        break;
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_INDEXED_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DISPATCH_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_NV_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_NV_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_DRAW_MESH_TASKS_COUNT_EXT:
    case VK_INDIRECT_COMMANDS_TOKEN_TYPE_TRACE_RAYS2_EXT:
        /* This selector has no union payload. */
        break;
    default:
        assert(false);
        break;
    }
}

/* struct VkIndirectCommandsLayoutTokenEXT chain */

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutTokenEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutTokenEXT_self(const VkIndirectCommandsLayoutTokenEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkIndirectCommandsTokenTypeEXT(&val->type);
    size += vn_sizeof_VkIndirectCommandsTokenDataEXT(&val->data, val->type);
    size += vn_sizeof_uint32_t(&val->offset);
    return size;
}

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutTokenEXT(const VkIndirectCommandsLayoutTokenEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectCommandsLayoutTokenEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectCommandsLayoutTokenEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectCommandsLayoutTokenEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectCommandsLayoutTokenEXT_self(struct vn_cs_encoder *enc, const VkIndirectCommandsLayoutTokenEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkIndirectCommandsTokenTypeEXT(enc, &val->type);
    vn_encode_VkIndirectCommandsTokenDataEXT(enc, &val->data, val->type);
    vn_encode_uint32_t(enc, &val->offset);
}

static inline void
vn_encode_VkIndirectCommandsLayoutTokenEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsLayoutTokenEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_TOKEN_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_TOKEN_EXT });
    vn_encode_VkIndirectCommandsLayoutTokenEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectCommandsLayoutTokenEXT_self(enc, val);
}

/* struct VkIndirectCommandsLayoutCreateInfoEXT chain */

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT_pnext(const void *val)
{
    const void *pnext = val;
    size_t size = 0;

    while (pnext) {
        switch ((int32_t)(*(const VkStructureType *)pnext)) {
        case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:
            size += vn_sizeof_simple_pointer(pnext);
            size += vn_sizeof_VkStructureType(pnext);
            size += vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT_pnext(((const VkPipelineLayoutCreateInfo *)pnext)->pNext);
            size += vn_sizeof_VkPipelineLayoutCreateInfo_self(pnext);
            return size;
        default:
            /* ignore unknown/unsupported struct */
            break;
        }
        memcpy(&pnext, (const char *)pnext + offsetof(VkBaseInStructure, pNext), sizeof(pnext));
    }

    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT_self(const VkIndirectCommandsLayoutCreateInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkFlags(&val->flags);
    size += vn_sizeof_VkFlags(&val->shaderStages);
    size += vn_sizeof_uint32_t(&val->indirectStride);
    size += vn_sizeof_VkPipelineLayout(&val->pipelineLayout);
    size += vn_sizeof_uint32_t(&val->tokenCount);
    if (val->pTokens) {
        size += vn_sizeof_array_size(val->tokenCount);
        for (uint32_t i = 0; i < val->tokenCount; i++)
            size += vn_sizeof_VkIndirectCommandsLayoutTokenEXT(&val->pTokens[i]);
    } else {
        size += vn_sizeof_array_size(0);
    }
    return size;
}

static inline size_t
vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT(const VkIndirectCommandsLayoutCreateInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectCommandsLayoutCreateInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    const void *pnext = val;

    while (pnext) {
        switch ((int32_t)(*(const VkStructureType *)pnext)) {
        case VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO:
            vn_encode_simple_pointer(enc, pnext);
            vn_encode_VkStructureType(enc, pnext);
            vn_encode_VkIndirectCommandsLayoutCreateInfoEXT_pnext(enc, ((const VkPipelineLayoutCreateInfo *)pnext)->pNext);
            vn_encode_VkPipelineLayoutCreateInfo_self(enc, pnext);
            return;
        default:
            /* ignore unknown/unsupported struct */
            break;
        }
        memcpy(&pnext, (const char *)pnext + offsetof(VkBaseInStructure, pNext), sizeof(pnext));
    }

    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectCommandsLayoutCreateInfoEXT_self(struct vn_cs_encoder *enc, const VkIndirectCommandsLayoutCreateInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkFlags(enc, &val->flags);
    vn_encode_VkFlags(enc, &val->shaderStages);
    vn_encode_uint32_t(enc, &val->indirectStride);
    vn_encode_VkPipelineLayout(enc, &val->pipelineLayout);
    vn_encode_uint32_t(enc, &val->tokenCount);
    if (val->pTokens) {
        vn_encode_array_size(enc, val->tokenCount);
        for (uint32_t i = 0; i < val->tokenCount; i++)
            vn_encode_VkIndirectCommandsLayoutTokenEXT(enc, &val->pTokens[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
}

static inline void
vn_encode_VkIndirectCommandsLayoutCreateInfoEXT(struct vn_cs_encoder *enc, const VkIndirectCommandsLayoutCreateInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_EXT });
    vn_encode_VkIndirectCommandsLayoutCreateInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectCommandsLayoutCreateInfoEXT_self(enc, val);
}

/* struct VkIndirectExecutionSetPipelineInfoEXT chain */

static inline size_t
vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT_self(const VkIndirectExecutionSetPipelineInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkPipeline(&val->initialPipeline);
    size += vn_sizeof_uint32_t(&val->maxPipelineCount);
    return size;
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT(const VkIndirectExecutionSetPipelineInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectExecutionSetPipelineInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectExecutionSetPipelineInfoEXT_self(struct vn_cs_encoder *enc, const VkIndirectExecutionSetPipelineInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkPipeline(enc, &val->initialPipeline);
    vn_encode_uint32_t(enc, &val->maxPipelineCount);
}

static inline void
vn_encode_VkIndirectExecutionSetPipelineInfoEXT(struct vn_cs_encoder *enc, const VkIndirectExecutionSetPipelineInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_PIPELINE_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_PIPELINE_INFO_EXT });
    vn_encode_VkIndirectExecutionSetPipelineInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectExecutionSetPipelineInfoEXT_self(enc, val);
}

/* struct VkIndirectExecutionSetShaderLayoutInfoEXT chain */

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT_self(const VkIndirectExecutionSetShaderLayoutInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_uint32_t(&val->setLayoutCount);
    if (val->pSetLayouts) {
        size += vn_sizeof_array_size(val->setLayoutCount);
        for (uint32_t i = 0; i < val->setLayoutCount; i++)
            size += vn_sizeof_VkDescriptorSetLayout(&val->pSetLayouts[i]);
    } else {
        size += vn_sizeof_array_size(0);
    }
    return size;
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT(const VkIndirectExecutionSetShaderLayoutInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT_self(struct vn_cs_encoder *enc, const VkIndirectExecutionSetShaderLayoutInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_uint32_t(enc, &val->setLayoutCount);
    if (val->pSetLayouts) {
        vn_encode_array_size(enc, val->setLayoutCount);
        for (uint32_t i = 0; i < val->setLayoutCount; i++)
            vn_encode_VkDescriptorSetLayout(enc, &val->pSetLayouts[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
}

static inline void
vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT(struct vn_cs_encoder *enc, const VkIndirectExecutionSetShaderLayoutInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_LAYOUT_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_LAYOUT_INFO_EXT });
    vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT_self(enc, val);
}

/* struct VkIndirectExecutionSetShaderInfoEXT chain */

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderInfoEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderInfoEXT_self(const VkIndirectExecutionSetShaderInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_uint32_t(&val->shaderCount);
    if (val->pInitialShaders) {
        size += vn_sizeof_array_size(val->shaderCount);
        for (uint32_t i = 0; i < val->shaderCount; i++)
            size += vn_sizeof_VkShaderEXT(&val->pInitialShaders[i]);
    } else {
        size += vn_sizeof_array_size(0);
    }
    if (val->pSetLayoutInfos) {
        size += vn_sizeof_array_size(val->shaderCount);
        for (uint32_t i = 0; i < val->shaderCount; i++)
            size += vn_sizeof_VkIndirectExecutionSetShaderLayoutInfoEXT(&val->pSetLayoutInfos[i]);
    } else {
        size += vn_sizeof_array_size(0);
    }
    size += vn_sizeof_uint32_t(&val->maxShaderCount);
    size += vn_sizeof_uint32_t(&val->pushConstantRangeCount);
    if (val->pPushConstantRanges) {
        size += vn_sizeof_array_size(val->pushConstantRangeCount);
        for (uint32_t i = 0; i < val->pushConstantRangeCount; i++)
            size += vn_sizeof_VkPushConstantRange(&val->pPushConstantRanges[i]);
    } else {
        size += vn_sizeof_array_size(0);
    }
    return size;
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetShaderInfoEXT(const VkIndirectExecutionSetShaderInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectExecutionSetShaderInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectExecutionSetShaderInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectExecutionSetShaderInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectExecutionSetShaderInfoEXT_self(struct vn_cs_encoder *enc, const VkIndirectExecutionSetShaderInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_uint32_t(enc, &val->shaderCount);
    if (val->pInitialShaders) {
        vn_encode_array_size(enc, val->shaderCount);
        for (uint32_t i = 0; i < val->shaderCount; i++)
            vn_encode_VkShaderEXT(enc, &val->pInitialShaders[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
    if (val->pSetLayoutInfos) {
        vn_encode_array_size(enc, val->shaderCount);
        for (uint32_t i = 0; i < val->shaderCount; i++)
            vn_encode_VkIndirectExecutionSetShaderLayoutInfoEXT(enc, &val->pSetLayoutInfos[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
    vn_encode_uint32_t(enc, &val->maxShaderCount);
    vn_encode_uint32_t(enc, &val->pushConstantRangeCount);
    if (val->pPushConstantRanges) {
        vn_encode_array_size(enc, val->pushConstantRangeCount);
        for (uint32_t i = 0; i < val->pushConstantRangeCount; i++)
            vn_encode_VkPushConstantRange(enc, &val->pPushConstantRanges[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
}

static inline void
vn_encode_VkIndirectExecutionSetShaderInfoEXT(struct vn_cs_encoder *enc, const VkIndirectExecutionSetShaderInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_SHADER_INFO_EXT });
    vn_encode_VkIndirectExecutionSetShaderInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectExecutionSetShaderInfoEXT_self(enc, val);
}

/* union VkIndirectExecutionSetInfoEXT */

static inline size_t
vn_sizeof_VkIndirectExecutionSetInfoEXT(const VkIndirectExecutionSetInfoEXT *val, VkIndirectExecutionSetInfoTypeEXT tag)
{
    size_t size = vn_sizeof_VkIndirectExecutionSetInfoTypeEXT(&tag);
    switch (tag) {
    case VK_INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT:
        size += vn_sizeof_simple_pointer(val->pPipelineInfo);
        if (val->pPipelineInfo)
            size += vn_sizeof_VkIndirectExecutionSetPipelineInfoEXT(val->pPipelineInfo);
        break;
    case VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT:
        size += vn_sizeof_simple_pointer(val->pShaderInfo);
        if (val->pShaderInfo)
            size += vn_sizeof_VkIndirectExecutionSetShaderInfoEXT(val->pShaderInfo);
        break;
    default:
        assert(false);
        break;
    }
    return size;
}

static inline void
vn_encode_VkIndirectExecutionSetInfoEXT(struct vn_cs_encoder *enc, const VkIndirectExecutionSetInfoEXT *val, VkIndirectExecutionSetInfoTypeEXT tag)
{
    vn_encode_VkIndirectExecutionSetInfoTypeEXT(enc, &tag);
    switch (tag) {
    case VK_INDIRECT_EXECUTION_SET_INFO_TYPE_PIPELINES_EXT:
        if (vn_encode_simple_pointer(enc, val->pPipelineInfo))
            vn_encode_VkIndirectExecutionSetPipelineInfoEXT(enc, val->pPipelineInfo);
        break;
    case VK_INDIRECT_EXECUTION_SET_INFO_TYPE_SHADER_OBJECTS_EXT:
        if (vn_encode_simple_pointer(enc, val->pShaderInfo))
            vn_encode_VkIndirectExecutionSetShaderInfoEXT(enc, val->pShaderInfo);
        break;
    default:
        assert(false);
        break;
    }
}

/* struct VkIndirectExecutionSetCreateInfoEXT chain */

static inline size_t
vn_sizeof_VkIndirectExecutionSetCreateInfoEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetCreateInfoEXT_self(const VkIndirectExecutionSetCreateInfoEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_VkIndirectExecutionSetInfoTypeEXT(&val->type);
    size += vn_sizeof_VkIndirectExecutionSetInfoEXT(&val->info, val->type);
    return size;
}

static inline size_t
vn_sizeof_VkIndirectExecutionSetCreateInfoEXT(const VkIndirectExecutionSetCreateInfoEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkIndirectExecutionSetCreateInfoEXT_pnext(val->pNext);
    size += vn_sizeof_VkIndirectExecutionSetCreateInfoEXT_self(val);

    return size;
}

static inline void
vn_encode_VkIndirectExecutionSetCreateInfoEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkIndirectExecutionSetCreateInfoEXT_self(struct vn_cs_encoder *enc, const VkIndirectExecutionSetCreateInfoEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_VkIndirectExecutionSetInfoTypeEXT(enc, &val->type);
    vn_encode_VkIndirectExecutionSetInfoEXT(enc, &val->info, val->type);
}

static inline void
vn_encode_VkIndirectExecutionSetCreateInfoEXT(struct vn_cs_encoder *enc, const VkIndirectExecutionSetCreateInfoEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_CREATE_INFO_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_INDIRECT_EXECUTION_SET_CREATE_INFO_EXT });
    vn_encode_VkIndirectExecutionSetCreateInfoEXT_pnext(enc, val->pNext);
    vn_encode_VkIndirectExecutionSetCreateInfoEXT_self(enc, val);
}

/* struct VkWriteIndirectExecutionSetPipelineEXT chain */

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT_self(const VkWriteIndirectExecutionSetPipelineEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_uint32_t(&val->index);
    size += vn_sizeof_VkPipeline(&val->pipeline);
    return size;
}

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT(const VkWriteIndirectExecutionSetPipelineEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT_pnext(val->pNext);
    size += vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT_self(val);

    return size;
}

static inline void
vn_encode_VkWriteIndirectExecutionSetPipelineEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkWriteIndirectExecutionSetPipelineEXT_self(struct vn_cs_encoder *enc, const VkWriteIndirectExecutionSetPipelineEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_uint32_t(enc, &val->index);
    vn_encode_VkPipeline(enc, &val->pipeline);
}

static inline void
vn_encode_VkWriteIndirectExecutionSetPipelineEXT(struct vn_cs_encoder *enc, const VkWriteIndirectExecutionSetPipelineEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_PIPELINE_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_PIPELINE_EXT });
    vn_encode_VkWriteIndirectExecutionSetPipelineEXT_pnext(enc, val->pNext);
    vn_encode_VkWriteIndirectExecutionSetPipelineEXT_self(enc, val);
}

/* struct VkWriteIndirectExecutionSetShaderEXT chain */

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetShaderEXT_pnext(const void *val)
{
    /* no known/supported struct */
    return vn_sizeof_simple_pointer(NULL);
}

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetShaderEXT_self(const VkWriteIndirectExecutionSetShaderEXT *val)
{
    size_t size = 0;
    /* skip val->{sType,pNext} */
    size += vn_sizeof_uint32_t(&val->index);
    size += vn_sizeof_VkShaderEXT(&val->shader);
    return size;
}

static inline size_t
vn_sizeof_VkWriteIndirectExecutionSetShaderEXT(const VkWriteIndirectExecutionSetShaderEXT *val)
{
    size_t size = 0;

    size += vn_sizeof_VkStructureType(&val->sType);
    size += vn_sizeof_VkWriteIndirectExecutionSetShaderEXT_pnext(val->pNext);
    size += vn_sizeof_VkWriteIndirectExecutionSetShaderEXT_self(val);

    return size;
}

static inline void
vn_encode_VkWriteIndirectExecutionSetShaderEXT_pnext(struct vn_cs_encoder *enc, const void *val)
{
    /* no known/supported struct */
    vn_encode_simple_pointer(enc, NULL);
}

static inline void
vn_encode_VkWriteIndirectExecutionSetShaderEXT_self(struct vn_cs_encoder *enc, const VkWriteIndirectExecutionSetShaderEXT *val)
{
    /* skip val->{sType,pNext} */
    vn_encode_uint32_t(enc, &val->index);
    vn_encode_VkShaderEXT(enc, &val->shader);
}

static inline void
vn_encode_VkWriteIndirectExecutionSetShaderEXT(struct vn_cs_encoder *enc, const VkWriteIndirectExecutionSetShaderEXT *val)
{
    assert(val->sType == VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_SHADER_EXT);
    vn_encode_VkStructureType(enc, &(VkStructureType){ VK_STRUCTURE_TYPE_WRITE_INDIRECT_EXECUTION_SET_SHADER_EXT });
    vn_encode_VkWriteIndirectExecutionSetShaderEXT_pnext(enc, val->pNext);
    vn_encode_VkWriteIndirectExecutionSetShaderEXT_self(enc, val);
}

static inline size_t vn_sizeof_vkGetGeneratedCommandsMemoryRequirementsEXT(VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkGetGeneratedCommandsMemoryRequirementsEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_simple_pointer(pInfo);
    if (pInfo)
        cmd_size += vn_sizeof_VkGeneratedCommandsMemoryRequirementsInfoEXT(pInfo);
    cmd_size += vn_sizeof_simple_pointer(pMemoryRequirements);
    if (pMemoryRequirements)
        cmd_size += vn_sizeof_VkMemoryRequirements2_partial(pMemoryRequirements);

    return cmd_size;
}

static inline void vn_encode_vkGetGeneratedCommandsMemoryRequirementsEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkGetGeneratedCommandsMemoryRequirementsEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    if (vn_encode_simple_pointer(enc, pInfo))
        vn_encode_VkGeneratedCommandsMemoryRequirementsInfoEXT(enc, pInfo);
    if (vn_encode_simple_pointer(enc, pMemoryRequirements))
        vn_encode_VkMemoryRequirements2_partial(enc, pMemoryRequirements);
}

static inline size_t vn_sizeof_vkGetGeneratedCommandsMemoryRequirementsEXT_reply(VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkGetGeneratedCommandsMemoryRequirementsEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip device */
    /* skip pInfo */
    cmd_size += vn_sizeof_simple_pointer(pMemoryRequirements);
    if (pMemoryRequirements)
        cmd_size += vn_sizeof_VkMemoryRequirements2(pMemoryRequirements);

    return cmd_size;
}

static inline void vn_decode_vkGetGeneratedCommandsMemoryRequirementsEXT_reply(struct vn_cs_decoder *dec, VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkGetGeneratedCommandsMemoryRequirementsEXT_EXT);

    /* skip device */
    /* skip pInfo */
    if (vn_decode_simple_pointer(dec)) {
        vn_decode_VkMemoryRequirements2(dec, pMemoryRequirements);
    } else {
        pMemoryRequirements = NULL;
    }
}

static inline size_t vn_sizeof_vkCreateIndirectCommandsLayoutEXT(VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectCommandsLayoutEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_simple_pointer(pCreateInfo);
    if (pCreateInfo)
        cmd_size += vn_sizeof_VkIndirectCommandsLayoutCreateInfoEXT(pCreateInfo);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);
    cmd_size += vn_sizeof_simple_pointer(pIndirectCommandsLayout);
    if (pIndirectCommandsLayout)
        cmd_size += vn_sizeof_VkIndirectCommandsLayoutEXT(pIndirectCommandsLayout);

    return cmd_size;
}

static inline void vn_encode_vkCreateIndirectCommandsLayoutEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectCommandsLayoutEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    if (vn_encode_simple_pointer(enc, pCreateInfo))
        vn_encode_VkIndirectCommandsLayoutCreateInfoEXT(enc, pCreateInfo);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
    if (vn_encode_simple_pointer(enc, pIndirectCommandsLayout))
        vn_encode_VkIndirectCommandsLayoutEXT(enc, pIndirectCommandsLayout);
}

static inline size_t vn_sizeof_vkCreateIndirectCommandsLayoutEXT_reply(VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectCommandsLayoutEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    VkResult ret;
    cmd_size += vn_sizeof_VkResult(&ret);
    /* skip device */
    /* skip pCreateInfo */
    /* skip pAllocator */
    cmd_size += vn_sizeof_simple_pointer(pIndirectCommandsLayout);
    if (pIndirectCommandsLayout)
        cmd_size += vn_sizeof_VkIndirectCommandsLayoutEXT(pIndirectCommandsLayout);

    return cmd_size;
}

static inline VkResult vn_decode_vkCreateIndirectCommandsLayoutEXT_reply(struct vn_cs_decoder *dec, VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkCreateIndirectCommandsLayoutEXT_EXT);

    VkResult ret;
    vn_decode_VkResult(dec, &ret);
    /* skip device */
    /* skip pCreateInfo */
    /* skip pAllocator */
    if (vn_decode_simple_pointer(dec)) {
        vn_decode_VkIndirectCommandsLayoutEXT(dec, pIndirectCommandsLayout);
    } else {
        pIndirectCommandsLayout = NULL;
    }

    return ret;
}

static inline size_t vn_sizeof_vkDestroyIndirectCommandsLayoutEXT(VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectCommandsLayoutEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_VkIndirectCommandsLayoutEXT(&indirectCommandsLayout);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);

    return cmd_size;
}

static inline void vn_encode_vkDestroyIndirectCommandsLayoutEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectCommandsLayoutEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    vn_encode_VkIndirectCommandsLayoutEXT(enc, &indirectCommandsLayout);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
}

static inline size_t vn_sizeof_vkDestroyIndirectCommandsLayoutEXT_reply(VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectCommandsLayoutEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip device */
    /* skip indirectCommandsLayout */
    /* skip pAllocator */

    return cmd_size;
}

static inline void vn_decode_vkDestroyIndirectCommandsLayoutEXT_reply(struct vn_cs_decoder *dec, VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkDestroyIndirectCommandsLayoutEXT_EXT);

    /* skip device */
    /* skip indirectCommandsLayout */
    /* skip pAllocator */
}

static inline size_t vn_sizeof_vkCreateIndirectExecutionSetEXT(VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectExecutionSetEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_simple_pointer(pCreateInfo);
    if (pCreateInfo)
        cmd_size += vn_sizeof_VkIndirectExecutionSetCreateInfoEXT(pCreateInfo);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);
    cmd_size += vn_sizeof_simple_pointer(pIndirectExecutionSet);
    if (pIndirectExecutionSet)
        cmd_size += vn_sizeof_VkIndirectExecutionSetEXT(pIndirectExecutionSet);

    return cmd_size;
}

static inline void vn_encode_vkCreateIndirectExecutionSetEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectExecutionSetEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    if (vn_encode_simple_pointer(enc, pCreateInfo))
        vn_encode_VkIndirectExecutionSetCreateInfoEXT(enc, pCreateInfo);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
    if (vn_encode_simple_pointer(enc, pIndirectExecutionSet))
        vn_encode_VkIndirectExecutionSetEXT(enc, pIndirectExecutionSet);
}

static inline size_t vn_sizeof_vkCreateIndirectExecutionSetEXT_reply(VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkCreateIndirectExecutionSetEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    VkResult ret;
    cmd_size += vn_sizeof_VkResult(&ret);
    /* skip device */
    /* skip pCreateInfo */
    /* skip pAllocator */
    cmd_size += vn_sizeof_simple_pointer(pIndirectExecutionSet);
    if (pIndirectExecutionSet)
        cmd_size += vn_sizeof_VkIndirectExecutionSetEXT(pIndirectExecutionSet);

    return cmd_size;
}

static inline VkResult vn_decode_vkCreateIndirectExecutionSetEXT_reply(struct vn_cs_decoder *dec, VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkCreateIndirectExecutionSetEXT_EXT);

    VkResult ret;
    vn_decode_VkResult(dec, &ret);
    /* skip device */
    /* skip pCreateInfo */
    /* skip pAllocator */
    if (vn_decode_simple_pointer(dec)) {
        vn_decode_VkIndirectExecutionSetEXT(dec, pIndirectExecutionSet);
    } else {
        pIndirectExecutionSet = NULL;
    }

    return ret;
}

static inline size_t vn_sizeof_vkDestroyIndirectExecutionSetEXT(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectExecutionSetEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_VkIndirectExecutionSetEXT(&indirectExecutionSet);
    cmd_size += vn_sizeof_simple_pointer(pAllocator);
    if (pAllocator)
        assert(false);

    return cmd_size;
}

static inline void vn_encode_vkDestroyIndirectExecutionSetEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectExecutionSetEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    vn_encode_VkIndirectExecutionSetEXT(enc, &indirectExecutionSet);
    if (vn_encode_simple_pointer(enc, pAllocator))
        assert(false);
}

static inline size_t vn_sizeof_vkDestroyIndirectExecutionSetEXT_reply(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkDestroyIndirectExecutionSetEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip pAllocator */

    return cmd_size;
}

static inline void vn_decode_vkDestroyIndirectExecutionSetEXT_reply(struct vn_cs_decoder *dec, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkDestroyIndirectExecutionSetEXT_EXT);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip pAllocator */
}

static inline size_t vn_sizeof_vkUpdateIndirectExecutionSetPipelineEXT(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetPipelineEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_VkIndirectExecutionSetEXT(&indirectExecutionSet);
    cmd_size += vn_sizeof_uint32_t(&executionSetWriteCount);
    if (pExecutionSetWrites) {
        cmd_size += vn_sizeof_array_size(executionSetWriteCount);
        for (uint32_t i = 0; i < executionSetWriteCount; i++)
            cmd_size += vn_sizeof_VkWriteIndirectExecutionSetPipelineEXT(&pExecutionSetWrites[i]);
    } else {
        cmd_size += vn_sizeof_array_size(0);
    }

    return cmd_size;
}

static inline void vn_encode_vkUpdateIndirectExecutionSetPipelineEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetPipelineEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    vn_encode_VkIndirectExecutionSetEXT(enc, &indirectExecutionSet);
    vn_encode_uint32_t(enc, &executionSetWriteCount);
    if (pExecutionSetWrites) {
        vn_encode_array_size(enc, executionSetWriteCount);
        for (uint32_t i = 0; i < executionSetWriteCount; i++)
            vn_encode_VkWriteIndirectExecutionSetPipelineEXT(enc, &pExecutionSetWrites[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
}

static inline size_t vn_sizeof_vkUpdateIndirectExecutionSetPipelineEXT_reply(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetPipelineEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip executionSetWriteCount */
    /* skip pExecutionSetWrites */

    return cmd_size;
}

static inline void vn_decode_vkUpdateIndirectExecutionSetPipelineEXT_reply(struct vn_cs_decoder *dec, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetPipelineEXT_EXT);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip executionSetWriteCount */
    /* skip pExecutionSetWrites */
}

static inline size_t vn_sizeof_vkUpdateIndirectExecutionSetShaderEXT(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetShaderEXT_EXT;
    const VkFlags cmd_flags = 0;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type) + vn_sizeof_VkFlags(&cmd_flags);

    cmd_size += vn_sizeof_VkDevice(&device);
    cmd_size += vn_sizeof_VkIndirectExecutionSetEXT(&indirectExecutionSet);
    cmd_size += vn_sizeof_uint32_t(&executionSetWriteCount);
    if (pExecutionSetWrites) {
        cmd_size += vn_sizeof_array_size(executionSetWriteCount);
        for (uint32_t i = 0; i < executionSetWriteCount; i++)
            cmd_size += vn_sizeof_VkWriteIndirectExecutionSetShaderEXT(&pExecutionSetWrites[i]);
    } else {
        cmd_size += vn_sizeof_array_size(0);
    }

    return cmd_size;
}

static inline void vn_encode_vkUpdateIndirectExecutionSetShaderEXT(struct vn_cs_encoder *enc, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetShaderEXT_EXT;

    vn_encode_VkCommandTypeEXT(enc, &cmd_type);
    vn_encode_VkFlags(enc, &cmd_flags);

    vn_encode_VkDevice(enc, &device);
    vn_encode_VkIndirectExecutionSetEXT(enc, &indirectExecutionSet);
    vn_encode_uint32_t(enc, &executionSetWriteCount);
    if (pExecutionSetWrites) {
        vn_encode_array_size(enc, executionSetWriteCount);
        for (uint32_t i = 0; i < executionSetWriteCount; i++)
            vn_encode_VkWriteIndirectExecutionSetShaderEXT(enc, &pExecutionSetWrites[i]);
    } else {
        vn_encode_array_size(enc, 0);
    }
}

static inline size_t vn_sizeof_vkUpdateIndirectExecutionSetShaderEXT_reply(VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites)
{
    const VkCommandTypeEXT cmd_type = VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetShaderEXT_EXT;
    size_t cmd_size = vn_sizeof_VkCommandTypeEXT(&cmd_type);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip executionSetWriteCount */
    /* skip pExecutionSetWrites */

    return cmd_size;
}

static inline void vn_decode_vkUpdateIndirectExecutionSetShaderEXT_reply(struct vn_cs_decoder *dec, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites)
{
    VkCommandTypeEXT command_type;
    vn_decode_VkCommandTypeEXT(dec, &command_type);
    assert(command_type == VK_COMMAND_TYPE_vkUpdateIndirectExecutionSetShaderEXT_EXT);

    /* skip device */
    /* skip indirectExecutionSet */
    /* skip executionSetWriteCount */
    /* skip pExecutionSetWrites */
}

static inline void vn_submit_vkGetGeneratedCommandsMemoryRequirementsEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkGetGeneratedCommandsMemoryRequirementsEXT(device, pInfo, pMemoryRequirements);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkGetGeneratedCommandsMemoryRequirementsEXT_reply(device, pInfo, pMemoryRequirements) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkGetGeneratedCommandsMemoryRequirementsEXT(enc, cmd_flags, device, pInfo, pMemoryRequirements);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkCreateIndirectCommandsLayoutEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkCreateIndirectCommandsLayoutEXT(device, pCreateInfo, pAllocator, pIndirectCommandsLayout);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkCreateIndirectCommandsLayoutEXT_reply(device, pCreateInfo, pAllocator, pIndirectCommandsLayout) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkCreateIndirectCommandsLayoutEXT(enc, cmd_flags, device, pCreateInfo, pAllocator, pIndirectCommandsLayout);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkDestroyIndirectCommandsLayoutEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkDestroyIndirectCommandsLayoutEXT(device, indirectCommandsLayout, pAllocator);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkDestroyIndirectCommandsLayoutEXT_reply(device, indirectCommandsLayout, pAllocator) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkDestroyIndirectCommandsLayoutEXT(enc, cmd_flags, device, indirectCommandsLayout, pAllocator);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkCreateIndirectExecutionSetEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkCreateIndirectExecutionSetEXT(device, pCreateInfo, pAllocator, pIndirectExecutionSet);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkCreateIndirectExecutionSetEXT_reply(device, pCreateInfo, pAllocator, pIndirectExecutionSet) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkCreateIndirectExecutionSetEXT(enc, cmd_flags, device, pCreateInfo, pAllocator, pIndirectExecutionSet);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkDestroyIndirectExecutionSetEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkDestroyIndirectExecutionSetEXT(device, indirectExecutionSet, pAllocator);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkDestroyIndirectExecutionSetEXT_reply(device, indirectExecutionSet, pAllocator) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkDestroyIndirectExecutionSetEXT(enc, cmd_flags, device, indirectExecutionSet, pAllocator);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkUpdateIndirectExecutionSetPipelineEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkUpdateIndirectExecutionSetPipelineEXT(device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkUpdateIndirectExecutionSetPipelineEXT_reply(device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkUpdateIndirectExecutionSetPipelineEXT(enc, cmd_flags, device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_submit_vkUpdateIndirectExecutionSetShaderEXT(struct vn_ring *vn_ring, VkCommandFlagsEXT cmd_flags, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites, struct vn_ring_submit_command *submit)
{
    uint8_t local_cmd_data[VN_SUBMIT_LOCAL_CMD_SIZE];
    void *cmd_data = local_cmd_data;
    size_t cmd_size = vn_sizeof_vkUpdateIndirectExecutionSetShaderEXT(device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites);
    if (cmd_size > sizeof(local_cmd_data)) {
        cmd_data = malloc(cmd_size);
        if (!cmd_data)
            cmd_size = 0;
    }
    const size_t reply_size = cmd_flags & VK_COMMAND_GENERATE_REPLY_BIT_EXT ? vn_sizeof_vkUpdateIndirectExecutionSetShaderEXT_reply(device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites) : 0;

    struct vn_cs_encoder *enc = vn_ring_submit_command_init(vn_ring, submit, cmd_data, cmd_size, reply_size);
    if (cmd_size) {
        vn_encode_vkUpdateIndirectExecutionSetShaderEXT(enc, cmd_flags, device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites);
        vn_ring_submit_command(vn_ring, submit);
        if (cmd_data != local_cmd_data)
            free(cmd_data);
    }
}

static inline void vn_call_vkGetGeneratedCommandsMemoryRequirementsEXT(struct vn_ring *vn_ring, VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    VN_TRACE_FUNC();

    struct vn_ring_submit_command submit;
    vn_submit_vkGetGeneratedCommandsMemoryRequirementsEXT(vn_ring, VK_COMMAND_GENERATE_REPLY_BIT_EXT, device, pInfo, pMemoryRequirements, &submit);
    struct vn_cs_decoder *dec = vn_ring_get_command_reply(vn_ring, &submit);
    if (dec) {
        vn_decode_vkGetGeneratedCommandsMemoryRequirementsEXT_reply(dec, device, pInfo, pMemoryRequirements);
        vn_ring_free_command_reply(vn_ring, &submit);
    }
}

static inline void vn_async_vkGetGeneratedCommandsMemoryRequirementsEXT(struct vn_ring *vn_ring, VkDevice device, const VkGeneratedCommandsMemoryRequirementsInfoEXT* pInfo, VkMemoryRequirements2* pMemoryRequirements)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkGetGeneratedCommandsMemoryRequirementsEXT(vn_ring, 0, device, pInfo, pMemoryRequirements, &submit);
}

static inline VkResult vn_call_vkCreateIndirectCommandsLayoutEXT(struct vn_ring *vn_ring, VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    VN_TRACE_FUNC();

    struct vn_ring_submit_command submit;
    vn_submit_vkCreateIndirectCommandsLayoutEXT(vn_ring, VK_COMMAND_GENERATE_REPLY_BIT_EXT, device, pCreateInfo, pAllocator, pIndirectCommandsLayout, &submit);
    struct vn_cs_decoder *dec = vn_ring_get_command_reply(vn_ring, &submit);
    if (dec) {
        const VkResult ret = vn_decode_vkCreateIndirectCommandsLayoutEXT_reply(dec, device, pCreateInfo, pAllocator, pIndirectCommandsLayout);
        vn_ring_free_command_reply(vn_ring, &submit);
        return ret;
    } else {
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    }
}

static inline void vn_async_vkCreateIndirectCommandsLayoutEXT(struct vn_ring *vn_ring, VkDevice device, const VkIndirectCommandsLayoutCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectCommandsLayoutEXT* pIndirectCommandsLayout)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkCreateIndirectCommandsLayoutEXT(vn_ring, 0, device, pCreateInfo, pAllocator, pIndirectCommandsLayout, &submit);
}

static inline void vn_async_vkDestroyIndirectCommandsLayoutEXT(struct vn_ring *vn_ring, VkDevice device, VkIndirectCommandsLayoutEXT indirectCommandsLayout, const VkAllocationCallbacks* pAllocator)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkDestroyIndirectCommandsLayoutEXT(vn_ring, 0, device, indirectCommandsLayout, pAllocator, &submit);
}

static inline VkResult vn_call_vkCreateIndirectExecutionSetEXT(struct vn_ring *vn_ring, VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    VN_TRACE_FUNC();

    struct vn_ring_submit_command submit;
    vn_submit_vkCreateIndirectExecutionSetEXT(vn_ring, VK_COMMAND_GENERATE_REPLY_BIT_EXT, device, pCreateInfo, pAllocator, pIndirectExecutionSet, &submit);
    struct vn_cs_decoder *dec = vn_ring_get_command_reply(vn_ring, &submit);
    if (dec) {
        const VkResult ret = vn_decode_vkCreateIndirectExecutionSetEXT_reply(dec, device, pCreateInfo, pAllocator, pIndirectExecutionSet);
        vn_ring_free_command_reply(vn_ring, &submit);
        return ret;
    } else {
        return VK_ERROR_OUT_OF_HOST_MEMORY;
    }
}

static inline void vn_async_vkCreateIndirectExecutionSetEXT(struct vn_ring *vn_ring, VkDevice device, const VkIndirectExecutionSetCreateInfoEXT* pCreateInfo, const VkAllocationCallbacks* pAllocator, VkIndirectExecutionSetEXT* pIndirectExecutionSet)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkCreateIndirectExecutionSetEXT(vn_ring, 0, device, pCreateInfo, pAllocator, pIndirectExecutionSet, &submit);
}

static inline void vn_async_vkDestroyIndirectExecutionSetEXT(struct vn_ring *vn_ring, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, const VkAllocationCallbacks* pAllocator)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkDestroyIndirectExecutionSetEXT(vn_ring, 0, device, indirectExecutionSet, pAllocator, &submit);
}

static inline void vn_async_vkUpdateIndirectExecutionSetPipelineEXT(struct vn_ring *vn_ring, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetPipelineEXT* pExecutionSetWrites)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkUpdateIndirectExecutionSetPipelineEXT(vn_ring, 0, device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites, &submit);
}

static inline void vn_async_vkUpdateIndirectExecutionSetShaderEXT(struct vn_ring *vn_ring, VkDevice device, VkIndirectExecutionSetEXT indirectExecutionSet, uint32_t executionSetWriteCount, const VkWriteIndirectExecutionSetShaderEXT* pExecutionSetWrites)
{
    struct vn_ring_submit_command submit;
    vn_submit_vkUpdateIndirectExecutionSetShaderEXT(vn_ring, 0, device, indirectExecutionSet, executionSetWriteCount, pExecutionSetWrites, &submit);
}

#endif /* VN_PROTOCOL_DRIVER_DEVICE_GENERATED_COMMANDS_H */
